#!/usr/bin/env python3

from pathlib import Path
import shutil


def is_wsl():
    try:
        with open("/proc/sys/kernel/osrelease") as f:
            return f.readline().strip().endswith("WSL2")
    except:
        return False


WSL = is_wsl()


def symlink(src, dst):
    if not dst.exists():
        print(f"Linking {src} -> {dst}")
        dst.symlink_to(src)


WIN_SDK_PATH = Path("/mnt/c/Program Files (x86)/Windows Kits/10")
MSVC_TOOLS_PATH = Path(
    "/mnt/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC")


def find_windows_sdk_version():
    latest = None

    for file in WIN_SDK_PATH.joinpath("Include").iterdir():
        if not latest or latest < file.name:
            latest = file.name

    if not latest:
        raise RuntimeError("failed to find Windows SDK")

    return latest


def find_msvc_tools_version():
    latest = None

    for file in MSVC_TOOLS_PATH.iterdir():
        if not latest or latest < file.name:
            latest = file.name

    if not latest:
        raise RuntimeError("failed to find msvc version")

    return latest


def setup_windows_sdk_libs():
    build_dir = Path("build/win")
    build_dir.mkdir(parents=True, exist_ok=True)

    msvc_version = find_msvc_tools_version()
    sdk_version = find_windows_sdk_version()

    msvc_dir = build_dir.joinpath("msvc")
    sdk_dir = build_dir.joinpath("sdk")
    sdk_version_file = build_dir.joinpath("sdk.version")

    required_files = [msvc_dir, sdk_dir, sdk_version_file]

    if all((f.exists() for f in required_files)):
        with open(sdk_version_file) as f:
            if f.read() == sdk_version:
                return

    print("WSL detected, assuming you are targeting Windows")

    print()
    print("Build Tools Versions")
    print("--------------------")
    print(f"MSVC Tools:  {msvc_version}")
    print(f"Windows SDK: {sdk_version}")
    print()

    symlink(MSVC_TOOLS_PATH.joinpath(msvc_version), msvc_dir)
    symlink(WIN_SDK_PATH, sdk_dir)

    with open(sdk_version_file, "w") as f:
        f.write(sdk_version)


if __name__ == "__main__":
    if WSL:
        setup_windows_sdk_libs()
