#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_DIR=$( dirname "$SCRIPT_DIR" )

cargo build --manifest-path "$PROJECT_DIR/Cargo.toml" --bin fuzzer --release

SCRIPT_DIR="$SCRIPT_DIR" "$PROJECT_DIR/target/release/fuzzer" "$@"
