name: docs

on:
  push:
    paths:
      - .github/workflows/docs.yml
      - docs/**
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install mdbook
        run: |
          curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.18/mdbook-v0.4.18-x86_64-unknown-linux-gnu.tar.gz > $HOME/mdbook.tar.gz
          sudo tar -xvf $HOME/mdbook.tar.gz -C /usr/bin

      - name: Install mdbook-admonish
        run: |
          curl -L https://github.com/tommilligan/mdbook-admonish/releases/download/v1.7.0/mdbook-admonish-v1.7.0-x86_64-unknown-linux-gnu.tar.gz > $HOME/mdbook-admonish.tar.gz
          sudo tar -xvf $HOME/mdbook-admonish.tar.gz -C /usr/bin

      - name: Install mdbook-toc
        run: |
          curl -L https://github.com/badboy/mdbook-toc/releases/download/0.9.0/mdbook-toc-0.9.0-x86_64-unknown-linux-gnu.tar.gz > $HOME/mdbook-toc.tar.gz
          sudo tar -xvf $HOME/mdbook-toc.tar.gz -C /usr/bin

      - name: Build docs
        working-directory: docs
        run: mdbook build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/book

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
